[default]
exten => 1001,1,Dial(PJSIP/1001)
exten => 1001,n,Hangup()

exten => 1002,1,Dial(PJSIP/1002)
exten => 1002,n,Hangup()

exten => 1000,1,Answer()
exten => 1000,n,Stasis(baat_bot)
exten => 1000,n,Hangup()
